ignore:
  - "**/*Controller.java"
coverage:
  status:
    patch:
      default:
        # basic
        target: 90%
        threshold: 0%
        paths: 
          - "!app/src/test/"
    project:
      default:
        # basic
        target: 90%
        threshold: 0%
        paths: 
          - "!app/src/test/"