coverage:
  status:
    patch:
      default:
        # basic
        target: 80%
        threshold: 0%
        paths: 
          - "!app/src/test/"
    project:
      default:
        # basic
        target: 80%
        threshold: 0%
        paths: 
          - "!app/src/test/"